# IMAGEN MODELO CREADA A PARTIR DE UNA YA EXISTENTE
FROM eclipse-temurin:23.0.2_7-jdk

#PUERTO 
EXPOSE 8080

#DEFINIR EL DIRECTORIO RAÍZ DEL CONTENEDOR
WORKDIR /root

#ARCHIVOS DEL CONTENEDOR
#EL PRIMER ARCHIVO QUE DEBEMOS COLOCAR ES pom.xml QUE CONTIENE LAS DEPENDENCIAS.
#COPIAMOS NUESTRO ARCHIVO EN LA CARPETA RAÍZ DEL CONTENEDOR
COPY ./pom.xml /root
#PARA EJECUTAR MAVEN EMBEBIDO
COPY ./.mvn /root.mvn
#COPIAR LOS EJECUTABLES DE MAVEN
COPY ./mvnw /root


#COPIAR EL CÓDIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /root/src


#LEVANTAR NUESTRA APP CUANDO INICIE CONTENEDOR
#EJECUTAR COMANDO SOLAMENTE CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/SpringDocker-0.0.1-SNAPSHOT.jar"]
