# IMAGEN MODELO CREADA A PARTIR DE UNA YA EXISTENTE
#FROM eclipse-temurin:23.0.2_7-jdk
FROM eclipse-temurin:23-jdk AS build

#PUERTO 
EXPOSE 8080

#DEFINIR EL DIRECTORIO RAÍZ DEL CONTENEDOR
WORKDIR /app

#ARCHIVOS DEL CONTENEDOR
#EL PRIMER ARCHIVO QUE DEBEMOS COLOCAR ES pom.xml QUE CONTIENE LAS DEPENDENCIAS.
#COPIAMOS NUESTRO ARCHIVO EN LA CARPETA RAÍZ DEL CONTENEDOR
COPY ./target/docker-compose.yml /app

COPY ./pom.xml /app
#PARA EJECUTAR MAVEN EMBEBIDO
COPY ./.mvn /app.mvn
#COPIAR LOS EJECUTABLES DE MAVEN
COPY ./mvnw /app


#COPIAR EL CÓDIGO FUENTE DENTRO DEL CONTENEDOR
COPY ./src /app/src


#LEVANTAR NUESTRA APP CUANDO INICIE CONTENEDOR
#EJECUTAR COMANDO SOLAMENTE CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/app/target/SpringDocker-0.0.1-SNAPSHOT.jar"]
